// export {default as HomeScreen} from "./Root/HomeScreen"
// export {default as LoginScreen} from "./LoginScreen"
export {default as ProfileScreen} from "./Root/ProfileScreen"
export {default as RegisterScreen} from "./RegisterScreen"
export {default as SettingsScreen} from "./SettingsScreen"
export {default as SplashScreen} from "./SplashScreen"
export {default as OnboardingScreen1} from "./OnboardingScreen/OnboardingScreen1"